package com.bookify.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    BOOK_NOT_FOUND,
    USER_NOT_FOUND,
    AUTHOR_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    REVIEW_NOT_FOUND,
    COLLECTION_NOT_FOUND,
    DUPLICATE_RESOURCE,
    DUPLICATE_EMAIL,
    DUPLICATE_ISBN,
    DUPLICATE_REVIEW,
    VALIDATION_FAILED,
    BAD_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_CREDENTIALS,
    EMAIL_NOT_VERIFIED,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    IMAGE_UPLOAD_FAILED,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_SERVER_ERROR
}
